set(_CATKIN_CURRENT_PACKAGE "zayas_test")
set(zayas_test_VERSION "0.0.2")
set(zayas_test_MAINTAINER "nuc <rayzayas@udel.edu>")
set(zayas_test_PACKAGE_FORMAT "2")
set(zayas_test_BUILD_DEPENDS "message_generation" "joy" "roscpp" "rospy" "std_msgs" "wfov_camera_msgs")
set(zayas_test_BUILD_EXPORT_DEPENDS "message_generation" "joy" "roscpp" "rospy" "std_msgs" "wfov_camera_msgs")
set(zayas_test_BUILDTOOL_DEPENDS "catkin")
set(zayas_test_BUILDTOOL_EXPORT_DEPENDS )
set(zayas_test_EXEC_DEPENDS "message_runtime" "joy" "roscpp" "rospy" "std_msgs" "wfov_camera_msgs")
set(zayas_test_RUN_DEPENDS "message_runtime" "joy" "roscpp" "rospy" "std_msgs" "wfov_camera_msgs" "message_generation")
set(zayas_test_TEST_DEPENDS )
set(zayas_test_DOC_DEPENDS )
set(zayas_test_URL_WEBSITE "")
set(zayas_test_URL_BUGTRACKER "")
set(zayas_test_URL_REPOSITORY "")
set(zayas_test_DEPRECATED "")