73: !!python/object/new:geometry_msgs.msg._Transform.Transform
  state:
  - !!python/object/new:geometry_msgs.msg._Vector3.Vector3
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        S5SiFXU4jL8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        RfxzoBrm0D8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        d0PJEHgNYT8=
  - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        VcWnDOesb78=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        9qhT5vPChj8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        pqUGEWSb5z8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        46qNfpSY5T8=
101: !!python/object/new:geometry_msgs.msg._Transform.Transform
  state:
  - !!python/object/new:geometry_msgs.msg._Vector3.Vector3
    state: [0.0, 0.0, 0.0]
  - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
    state: [0.0, 0.0, 0.0, 1]
