2: !!python/object/new:geometry_msgs.msg._Transform.Transform
  state:
  - !!python/object/new:geometry_msgs.msg._Vector3.Vector3
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!python/str "\uBBF3\ek(\u023F"
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        DD4YLNbPmj8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        VeRTy7i9WL8=
  - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        Je0ZmvYrc78=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        hCzHCUtTf78=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        fGy5qXyejb8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        KdZBoX7+7z8=
101: !!python/object/new:geometry_msgs.msg._Transform.Transform
  state:
  - !!python/object/new:geometry_msgs.msg._Vector3.Vector3
    state: [0.0, 0.0, 0.0]
  - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
    state: [0.0, 0.0, 0.0, 1]
