1: !!python/object/new:geometry_msgs.msg._Transform.Transform
  state:
  - !!python/object/new:geometry_msgs.msg._Vector3.Vector3
    state: [0.0, 0.0, 0.0]
  - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
    state: [0.0, 0.0, 0.0, 1]
2: !!python/object/new:geometry_msgs.msg._Transform.Transform
  state:
  - !!python/object/new:geometry_msgs.msg._Vector3.Vector3
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        1Oo5Sgx61j8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        INFfUuCKk78=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        AEyFw40AW78=
  - !!python/object/new:geometry_msgs.msg._Quaternion.Quaternion
    state:
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        sL/trwjgk78=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        3IkBNnp5hr8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        GAz9/1/2FL8=
    - !!python/object/apply:numpy.core.multiarray.scalar
      - !!python/object/apply:numpy.dtype
        args: [f8, 0, 1]
        state: !!python/tuple [3, <, null, null, null, -1, -1, 0]
      - !!binary |
        2nuuofb97z8=
